#!/bin/bash
#PBS -l nodes=1:ppn=16 -q xeon16
#PBS -N pdos_NBTO_vol
#PBS -e .ERROR
#PBS -o .OUT
CODE=/usr/local/cluster_programs/espresso-5.3.0/bin
# run from directory where this script is
#cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
cd "$PBS_O_WORKDIR"
# Run the Application
NUM_NODES=$(uniq $PBS_NODEFILE | wc -l)
mpdboot -n $NUM_NODES -v -r ssh -f $PBS_NODEFILE

# Run the Application
export OMP_NUM_THREADS=$PBS_NP
PSEUDO_DIR=`.`
TMP_DIR=`.`

# required executables and pseudopotentials
BIN_LIST="pw.x pp.x plotrho.x projwfc.x sumpdos.x"
PSEUDO_LIST="Al.pz-vbc.UPF As.pz-bhs.UPF"
BIN_DIR=


# how to run executables
PW_COMMAND=pw.x 
PP_COMMAND=pp.x 
PLOTRHO_COMMAND=plotrho.x
PROJWFC_COMMAND=projwfc.x 
SUMPDOS_COMMAND=sumpdos.x

# self-consistent calculation
cat > NBTOre.scf.in << EOF
 &control
    calculation = 'scf'
    restart_mode='from_scratch',
    title='NBTO'
    pseudo_dir = '.',
    outdir='.',
    prefix='NBTO'
 /
 &system
    ibrav =  5, 
    celldm(1) = 10.5427, celldm(4) = 0.5127
    nat =  10, 
    ntyp = 4,
    ecutwfc = 430
    occupations = 'fixed'
 /
 &electrons
    mixing_beta = 0.7
    diagonalization = 'david'
    conv_thr = 1e-9
 /
 ATOMIC_SPECIES
 Bi 208.980 Bi.pbe-d-mt.UPF
 Na 22.9898 Na.pbe-sp-hgh.UPF
 Ti 47.867  Ti.pbe-mt_fhi.UPF
 O  15.999  O.pbe-mt.UPF
ATOMIC_POSITIONS
Bi 0.218350      0.218351      0.218350
Na 0.728870      0.728871      0.728870
Ti 0.488363      0.488363      0.488363
Ti 0.984806      0.984808      0.984806
O  0.195409      0.311763      0.765647
O  0.814013      0.691746      0.252633
O  0.765647      0.195410      0.311763
O  0.311763      0.765648      0.195409
O  0.252633      0.814014      0.691745
O  0.691745      0.252634      0.814013
K_POINTS {automatic}
 6 6 6 0 0 0
EOF

mpiexec -np 16 $CODE/$PW_COMMAND < NBTOre.scf.in > NBTOre.scf.out







cat > AlAs110re.nonscf.in << EOF
 &control
    calculation = 'nscf'
    restart_mode='from_scratch',
    title='AlAs 110 surface slab, relaxed (central plane fixed)'
    pseudo_dir = '.',
    outdir='.',
    prefix='AlAs110'
 /
 &system
    ibrav=  8, celldm(1) =7.424621202, celldm(2)=1.414213576,
    celldm(3)= 6.00000,
    nat= 14, ntyp= 2,
    occupations='smearing', smearing='gaussian', degauss=0.01, nbnd=34,
    ecutwfc =14.0,
 /
 &electrons
    mixing_mode = 'plain'
    mixing_beta = 0.7
    conv_thr =  1.0d-6
 /
 ATOMIC_SPECIES
 Al  26.98  Al.pz-vbc.UPF
 As  74.92  As.pz-bhs.UPF
ATOMIC_POSITIONS
 As  0.000000000  -0.044777195  -0.058158722
 Al  0.500000000   0.251460333   0.113525468
 As  0.500000000   0.712279009   0.504183885
 Al  0.000000000   1.067633546   0.480460620
 As  0.000000000  -0.003937059   0.995826731
 Al  0.500000000   0.351400965   1.004220212
 As  0.000000000  -0.003937059   2.004173269
 Al  0.500000000   0.351400965   1.995779788
 As  0.500000000   0.712279009   2.495816115
 Al  0.000000000   1.067633546   2.519539380
 As  0.000000000  -0.044777195   3.058158722
 Al  0.500000000   0.251460333   2.886474532
 As  0.500000000   0.707106800   1.500000000
 Al  0.000000000   1.060660200   1.500000000
K_POINTS {automatic}
 12 4 1 0 0 0
EOF
mpiexec -np 16 $CODE/$PW_COMMAND < AlAs110re.nonscf.in > AlAs110re.nonscf.out




# post-processing for stm images (sample bias given in Ry!)
cat > AlAs110.pp_stm-.in << EOF
 &inputpp
    prefix  = 'AlAs110'
    outdir='.',
    filplot = 'AlAsresm-1.0'
    sample_bias=-0.0735d0,
    plot_num= 5
 /
 &plot
   nfile=1
   filepp(1)='AlAsresm-1.0'
   weight(1)=1.0
   iflag=2
   output_format=2
   e1(1)=7.0, e1(2)=0.0,     e1(3)=0.0
   e2(1)=0.0, e2(2)=7.07107, e2(3)=0.0
   x0(1)=0.0, x0(2)=-0.18,   x0(3)=3.25
   nx=36 ,ny=56
   fileout='AlAs110-1.0'
 /
EOF

mpiexec -np 16 $CODE/$PP_COMMAND < AlAs110.pp_stm-.in > AlAs110.pp_stm-.out









# run plotrho to do the figure
cat > AlAs110.plotrho-.in << EOF
AlAs110-1.0
AlAs110-1.0eV.ps
n
0.00005 0.0078  8
EOF


mpiexec -np 16 $CODE/$PLOTRHO_COMMAND < AlAs110.plotrho-.in > AlAs110.plotrho-.out


# post-processing for stm images (negative bias, constant current)
cat > AlAs110.pp_isostm-.in << EOF
 &inputpp
 /
 &plot
    nfile=1
    filepp(1)='AlAsresm-1.0'
    weight(1)=1.0
    iflag=2
    output_format=7    
    fileout='AlAs110.pp_isostm-.dat'
    e1(1)=7.0, e1(2)=0.0,     e1(3)=0.0
    e2(1)=0.0, e2(2)=7.07107, e2(3)=0.0
    nx=150, ny=150
    isostm_flag=.true.
    isovalue=0.00005
    heightmin=0.4
    heightmax=0.75
    direction=1
 /
EOF


mpiexec -np 16 $CODE/$PP_COMMAND < AlAs110.pp_isostm-.in > AlAs110.pp_isostm-.out


# run gnuplot to do the figure

cat > gnuplot.tmp <<EOF
set term postscript enhanced color solid lw 3 24
set output 'AlAs110-1.0eV.isoplot.ps'
set xlabel "x (bohr)"
set ylabel "y (bohr)"
set pm3d map
set size ratio -1
set palette rgb 21,22,23
set tics out
unset key
splot [0:51.972][0:52.500] 'AlAs110.pp_isostm-.dat'
EOF

gnuplot < gnuplot.tmp

rm gnuplot.tmp
fi










# Projection of the DOS on volumes (boxes)
cat > AlAs110.box.projwfc.in << EOF
 &projwfc
    prefix  = 'AlAs110'
    outdir='.',
    ngauss=0
    degauss=0.01
    DeltaE=0.02
    tdosinboxes=.true.
    plotboxes=.true.
    n_proj_boxes=8

!! Boxes centered on the first vacuum layer:
  !! 1) above the surface Al
    irmin(1,1)= 0, irmax(1,1)= 2, irmin(2,1)= 0, irmax(2,1)= 2, irmin(3,1)=63, irmax(3,1)=65,
  !! 2) above the surface As
    irmin(1,2)= 9, irmax(1,2)=11, irmin(2,2)= 5, irmax(2,2)= 7, irmin(3,2)=63, irmax(3,2)=65,
  !! 3) above the 2nd layer Al
    irmin(1,3)= 9, irmax(1,3)=11, irmin(2,3)=14, irmax(2,3)=16, irmin(3,3)=63, irmax(3,3)=65,
  !! 4) as large as the surface unit cell
    irmin(1,4)= 1, irmax(1,4)=18, irmin(2,4)= 1, irmax(2,4)=27, irmin(3,4)=63, irmax(3,4)=65,

!! Same as above, centered on the second vacuum layer:
    irmin(1,5)= 0, irmax(1,5)= 2, irmin(2,5)= 0, irmax(2,5)= 2, irmin(3,5)=72, irmax(3,5)=74,
    irmin(1,6)= 9, irmax(1,6)=11, irmin(2,6)= 5, irmax(2,6)= 7, irmin(3,6)=72, irmax(3,6)=74,
    irmin(1,7)= 9, irmax(1,7)=11, irmin(2,7)=14, irmax(2,7)=16, irmin(3,7)=72, irmax(3,7)=74,
    irmin(1,8)= 1, irmax(1,8)=18, irmin(2,8)= 1, irmax(2,8)=27, irmin(3,8)=72, irmax(3,8)=74,
 /
EOF

mpiexec -np 16 $CODE/$PROJWFC_COMMAND < AlAs110.box.projwfc.in > AlAs110.box.projwfc.out



# Projection of the DOS on atomic wavefunctions
cat > AlAs110.projwfc.in << EOF
 &projwfc
    prefix  = 'AlAs110'
    outdir='.',
    ngauss=0
    degauss=0.01
    DeltaE=0.02
    tdosinboxes=.false.
 /
EOF

mpiexec -np 16 $CODE/$PROJWFC_COMMAND < AlAs110.projwfc.in > AlAs110.projwfc.out

mpiexec -np 16 $CODE/$SUMPDOS_COMMAND AlAs110.pdos_atm\#10\(Al\)_wfc* > "AlAs110.pdos_atm#10(Al)" 2> /dev/null
mpiexec -np 16 $CODE/$SUMPDOS_COMMAND AlAs110.pdos_atm\#11\(As\)_wfc* > "AlAs110.pdos_atm#11(As)" 2> /dev/null


eFermi=`grep "Fermi" AlAs110re.nonscf.out | cut -d  \  -f 14`
cat > gnuplot.tmp <<EOF
set term postscript enhanced color solid lw 3 24
set output 'AlAs110.box.projwfc.ps'
ef=$eFermi
set xlabel "Energy - E_F (eV)"
set ylabel "Local DOS (states/eV)"
set style data lines
set key top left Left reverse
set border 31 lw 0.2
set title "Projected DOS"
plot \\
 './AlAs110.pdos_atm#10(Al)' u (\$1-ef):2 t "Surface Al" ,\\
 './AlAs110.pdos_atm#11(As)' u (\$1-ef):2 t "Surface As"
set title "Local DOS centered in the first vacuum layer"
plot \\
 './AlAs110.ldos_boxes' u (\$1-ef):4 t "Above Al" ,\\
 './AlAs110.ldos_boxes' u (\$1-ef):5 t "Above As" ,\\
 './AlAs110.ldos_boxes' u (\$1-ef):(\$7/54) t "Surface average"
set title "Local DOS centered in the second vacuum layer"
plot \\
 './AlAs110.ldos_boxes' u (\$1-ef):8 t "Above Al" ,\\
 './AlAs110.ldos_boxes' u (\$1-ef):9 t "Above As" ,\\
 './AlAs110.ldos_boxes' u (\$1-ef):(\$11/54) t "Surface average"
EOF
gnuplot < gnuplot.tmp

rm gnuplot.tmp
fi


### To visualize a volume in which the DOS is integrated, execute:"
###   xcrysden --xsf results/AlAs110.box#1.xsf"



# clean TMP_DIR




mpdallexi
