#!/bin/bash
#PBS -l nodes=1:ppn=16 -q xeon16
#PBS -N pdos_NBTO_vol
#PBS -e .ERROR
#PBS -o .OUT
CODE=/usr/local/cluster_programs/espresso-5.3.0/bin
# run from directory where this script is
#cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
cd "$PBS_O_WORKDIR"
# Run the Application
NUM_NODES=$(uniq $PBS_NODEFILE | wc -l)
mpdboot -n $NUM_NODES -v -r ssh -f $PBS_NODEFILE

# Run the Application
export OMP_NUM_THREADS=$PBS_NP
PSEUDO_DIR=`.`
TMP_DIR=`.`

# required executables and pseudopotentials
BIN_LIST="pw.x pp.x plotrho.x projwfc.x sumpdos.x"
PSEUDO_LIST="Al.pz-vbc.UPF As.pz-bhs.UPF"
BIN_DIR=


# how to run executables
PW_COMMAND=pw.x 
PP_COMMAND=pp.x 
PLOTRHO_COMMAND=plotrho.x
PROJWFC_COMMAND=projwfc.x 
SUMPDOS_COMMAND=sumpdos.x

# self-consistent calculation
cat > AlAs110re.scf.in << EOF
 &control
    calculation = 'scf'
    restart_mode='from_scratch',
    title='AlAs 110 surface slab, relaxed (central plane fixed)'
    pseudo_dir = '.',
    outdir='.',
    prefix='AlAs110'
 /
 &system
    ibrav=  8, celldm(1) =7.424621202, celldm(2)=1.414213576,
    celldm(3)= 6.00000,
    nat= 14, ntyp= 2,
    ecutwfc =14.0,
 /
 &electrons
    mixing_mode = 'plain'
    mixing_beta = 0.7
    conv_thr =  1.0d-6
 /
 ATOMIC_SPECIES
 Al  26.98  Al.pz-vbc.UPF
 As  74.92  As.pz-bhs.UPF
ATOMIC_POSITIONS
 As  0.000000000  -0.044777195  -0.058158722
 Al  0.500000000   0.251460333   0.113525468
 As  0.500000000   0.712279009   0.504183885
 Al  0.000000000   1.067633546   0.480460620
 As  0.000000000  -0.003937059   0.995826731
 Al  0.500000000   0.351400965   1.004220212
 As  0.000000000  -0.003937059   2.004173269
 Al  0.500000000   0.351400965   1.995779788
 As  0.500000000   0.712279009   2.495816115
 Al  0.000000000   1.067633546   2.519539380
 As  0.000000000  -0.044777195   3.058158722
 Al  0.500000000   0.251460333   2.886474532
 As  0.500000000   0.707106800   1.500000000
 Al  0.000000000   1.060660200   1.500000000
K_POINTS {automatic}
 6 2 1 0 0 0
EOF

mpiexec -np 16 $CODE/$PW_COMMAND < AlAs110re.scf.in > AlAs110re.scf.out
mpdallexi


